Initial bemenu module
danth/stylix pull request #11
Opened 2022-08-04 18:56 UTC by Lyndeno

Initial bemenu config with sane defaults. Sets the options via BEMENU_OPTS so they can also be overridden.

Includes optional settings such as ```fontSize``` and ```alternate```. These options can be set to adjust certain settings in bemenu.

2022-08-04 22:14 UTC, danth requested changes
Documentation didn't like the settings with no description - but I've sorted that out now. Rebasing this on master should make the checks pass.

2022-08-04 22:14 UTC, danth commented on modules/bemenu.nix
> +    fontSize = lib.mkOption { type = lib.types.str; default = ""; }; # optional argument
This should probably be `int` type:

```suggestion
    fontSize = lib.mkOption {
      type = with lib.types; nullOr int;
      default = null;
    };
```

Then convert it to the appropriate string where it's needed:

```nix
${lib.optionalString (fontSize != null) (builtins.toString fontSize)}
```

It's a bit more wordy, but it catches potential mistakes like setting `"bold"` as the font size.

2022-08-04 22:14 UTC, danth commented on modules/bemenu.nix
> +  config.home-manager.sharedModules = lib.mkIf config.stylix.targets.mako.enable [{
Almost missed this one!

```suggestion
  config.home-manager.sharedModules = lib.mkIf config.stylix.targets.bemenu.enable [{
```

2022-08-10 18:47 UTC, Lyndeno commented
Made some updates including your changes

2022-08-10 19:13 UTC, danth approved these changes
Thanks!

2022-08-10 19:13 UTC, merged