hyprland: adjust colors
danth/stylix pull request #414
Opened 2024-06-04 20:49 UTC by diniamo

This makes the most sense to me, I feel like blue is the "most default" accent color. As for groups, the active and inactive colors should be the same, since they are still windows, while the locked active color is a slightly modified active color (at least in catppuccin, it's teal instead of blue).

2024-06-05 13:22 UTC, danth requested changes
Having active windows use blue to match the accent color of other applications makes sense to me.

However, we also need to update the [style guide](https://danth.github.io/stylix/styling.html#window-managers) with these new preferences, as well as changing other window managers to use the new colors, so that we are consistent.

From a quick look through the module list, I think these are all the files which will need to be updated:

- [The style guide](https://github.com/danth/stylix/blob/1d3826ceed91ae67562f28ee2e135813a11e47a6/docs/src/styling.md)
- [bspwm](https://github.com/danth/stylix/blob/1d3826ceed91ae67562f28ee2e135813a11e47a6/modules/bspwm/hm.nix)
- [i3](https://github.com/danth/stylix/blob/1d3826ceed91ae67562f28ee2e135813a11e47a6/modules/i3/hm.nix)
- [Sway](https://github.com/danth/stylix/blob/1d3826ceed91ae67562f28ee2e135813a11e47a6/modules/sway/hm.nix)

2024-06-06 15:41 UTC, diniamo commented
Please check this thoroughly, I'm the least sure about bspwm

2024-06-06 17:41 UTC, trueNAHO approved these changes
I did not test this, but LGTM.

In the future, https://github.com/danth/stylix/issues/249 should resolve these kind of inconsistencies.

2024-06-06 20:26 UTC, diniamo commented
(Only reworded the commit)

2024-06-08 15:17 UTC, danth approved these changes

2024-06-08 15:17 UTC, merged