Add bspwm module
danth/stylix pull request #44
Opened 2023-02-25 21:24 UTC by dwarfmaster

There are a few things to discuss. The actual theme has been copied from [base16-builder](https://github.com/base16-builder/base16-builder), which had two templates, one for dark schemes and one for light ones. I kept the distinction but is it really something we want ?
Furthermore, I find that using `base08` as the focused window border color a bit too agressive, but I'd like other opinion.

Would close #39

2023-02-26 03:09 UTC, realsnick commented
Great, I will give it a try as soon as this nvidia build fixes itself. 

in addition, can you help me understand each base and what is being used for?  as i know some are being used for alerts/warning as mentioned base08

I've collected the following below but not sure if this is accurate or not

# Neutral Colors:
# Darkest color, used for the background color of the application or text editor.
base00: ""

# Slightly lighter color, used for borders, lines, and other subtle design elements.
base01: ""

# Lighter color, used for syntax highlighting elements such as comments or preprocessor directives.
base02: ""

# Lightest neutral color, used for plain text or background text.
base03: ""

# Accent Colors:
# First accent color, used to highlight important elements in the interface such as selected text or active buttons.
base04: ""

# Lighter accent color, used for less important interface elements such as inactive buttons or secondary text.
base05: ""

# Second accent color, used to highlight additional important elements in the interface such as warning or error messages.
base06: ""

# Lightest accent color, used for less important highlighted elements such as less critical warning or status messages.
base07: ""
# Bright Colors:
# First bright color, used for syntax highlighting elements such as keywords or function names.
base08: ""

# Slightly lighter bright color, used for syntax highlighting elements such as numeric constants or string literals.
base09: ""

# Lighter version of base09, used for syntax highlighting elements such as escape characters or special symbols.
base0A: ""

# Second bright color, used for syntax highlighting elements such as operators or punctuation.
base0B: ""

# Color used for syntax highlighting elements such as function arguments or types.
base0C: ""

# Color used for syntax highlighting elements such as variables or class names.
base0D: ""

# Color used for syntax highlighting elements such as constants or enums.
base0E: ""

# Last bright color, used for syntax highlighting elements such as macros or other preprocessor directives.
base0F: ""

2023-02-26 03:10 UTC, realsnick commented
also found these

```
Base00/Background: Used as a primary background color and can be used for subtle glow or light shadow effects; also used as a default color for text.
Base01/Current Line: Used as a highlight color for borders and shadows, or as a start color for subtle gradients; can also be used as a muted color for text.
Base02/Selection: Used as a color for borders, shadows, and drop shadows, or as an end color for gradients; can also be used for highlighting text.
Base03/Comment: Used as a secondary or muted color for borders, shadows, and gradients; can also be used for comments or annotations in text.
Base04/String: Used as a color for attention-grabbing or high-contrast borders, shadows, and gradients; can also be used to highlight or emphasize text.
Base05/Foreground: Used as a default color for borders, shadows, and text; can also be used as a neutral color for gradients.
Base06/Variable: Used as a color for subtle or secondary borders and shadows, or as a muted color for gradients; can also be used for highlighting or styling variable names in text.
Base07/Cursor: Used as a color for subtle or secondary borders and shadows, or as a highlight color for gradients; can also be used as a cursor color in text editors.
Base08/Red: Used as a color for borders, shadows, or gradients that indicate danger, criticality, or urgency; can also be used to indicate errors or warnings in text.
Base09/Orange: Used as a color for highlighting important information or elements in a GUI or application, as well as for styling text that requires attention or emphasis.
Base0A/Yellow: Used as a color for highlighting keywords or important information in various contexts, as well as for styling text that requires attention or emphasis.
Base0B/Green: Used as a color for indicating success, completion, or positive feedback in various contexts, as well as for styling text that indicates progress or status.
Base0C/Cyan: Used as a color for indicating methods, functions, or other related elements in various contexts, as well as for styling text that requires a technical or scientific tone.
Base0D/Blue: Used as a color for indicating links, navigation, or interactive elements in various contexts, as well as for styling text that requires a creative or imaginative tone.
Base0E/Purple: Used as a color for indicating numbers, data, or quantitative information in various contexts, as well as for styling text that indicates luxury or extravagance.
Base0F/Brown: Used as a color for indicating warnings, errors, or critical information in various contexts, as well as for styling text that indicates stability, reliability, or consistency.```

2023-02-26 03:27 UTC, realsnick commented
what is the syntax to point stylix.url to this commit?

2023-02-26 06:53 UTC, realsnick requested changes
Seems to look good. 

as for the configuration, only these works:
```
active_border_color 
normal_border_color 
focused_border_color 
presel_feedback_color
```
rest have an error with bspwmrc so can be removed.

2023-02-26 14:45 UTC, danth commented
> two templates, one for dark schemes and one for light ones. I kept the distinction but is it really something we want ?

`stylix.polarity` doesn't necessarily tell us the lightness, as it defaults to `either`, and is not updated when choosing a premade theme. This is an issue with some existing modules too.

> can you help me understand each base and what is being used for?

[This table](https://github.com/chriskempson/base16/blob/main/styling.md) has some information on that, although its mainly focused on syntax highlighting.

> what is the syntax to point stylix.url to this commit?

`github:dwarfmaster/stylix/bspwm` will fetch the latest commit from this branch.

2023-02-26 19:51 UTC, dwarfmaster commented
I guess we can drop the distinction between light and dark themes, it should be symmetric anyway. I'll test it with a light theme to be sure (my default theme is dark).
You're right about the other settings not existing, I didn't notice the errors in my logs. If there are only 4 to set it makes it a lot easier to chose. I'll try to propose an update tonight or tomorrow.

2023-02-27 17:25 UTC, dwarfmaster commented
What do you think now ? I removed the useless theming. We definitely want `presel_feedback_color` to have the same color as `active_border_color`. @realsnick If that looks good to you I'll merge it as is.

2023-02-27 20:23 UTC, realsnick commented
thanks! looks good

2023-02-28 08:21 UTC, danth approved these changes
LGTM

2023-02-28 15:13 UTC, merged