Fix opacity darwin and rm fontDir + rename fonts.fonts to fonts.packages
danth/stylix pull request #441
Opened 2024-06-18 21:46 UTC by NewDawn0

## Scope
- Fix [opacity issue](https://github.com/danth/stylix/issues/440)
- Fix `fonts.fonts` has been renamed to `fonts.packages`
- Fix `fonts.fontDir` has been deprecated

## Motivation
This PR adresses the several issues:
Firstly, the opacity issue on darwin [opacity issue](https://github.com/danth/stylix/issues/440).
And secondly, the deprecation of the fontDir option as well as the renaming of `fonts.fonts` to `fonts.packages`

2024-06-18 21:52 UTC, NewDawn0 commented
I looked at the other open PRs and this would fix not only the afforementioned issue but would implement [this PR](https://github.com/danth/stylix/pull/439) changes aswell

2024-06-19 09:04 UTC, trueNAHO requested changes
> This PR adresses the several issues:
>
> Firstly, the opacity issue on darwin [opacity issue](https://github.com/danth/stylix/issues/440).
>
> And secondly, the deprecation of the fontDir option as well as the renaming of `fonts.fonts` to `fonts.packages`

IMHO, it might be better to merge this PR (opacity issue) and https://github.com/danth/stylix/pull/439 (renaming `fonts.fonts`) seperately.

Considering that https://github.com/danth/stylix/issues/236 eventually resolves formatting concerns, it might be better to simplify this PR diff by only keeping the https://github.com/danth/stylix/pull/441/commits/26f5ea4f8a4cb28bfa638510a1acc7cfccc667d3 commit.

2024-06-20 13:38 UTC, NewDawn0 commented
Alright I did a hard reset to [import opacity](https://github.com/NewDawn0/stylix/commit/26f5ea4f8a4cb28bfa638510a1acc7cfccc667d3)

2024-06-23 14:17 UTC, trueNAHO approved these changes
LGTM

2024-06-23 14:19 UTC, merged