neovim: init
danth/stylix pull request #496
Opened 2024-08-03 19:51 UTC by donovanglover

Closes #471

2024-08-04 14:09 UTC, trueNAHO requested changes
I have successfully tested that this PR does not interfere with NixVim when Neovim is disabled.

Consider taking inspiration from the very similar [NixVim implementation](https://github.com/danth/stylix/blob/feb2973dfa8232c07efbd2b48f11a5cfa2276570/modules/nixvim/nixvim.nix).

2024-08-05 14:38 UTC, trueNAHO approved these changes
LGTM

2024-08-05 16:03 UTC, danth reviewed
LGTM in terms of separating the two targets - please consider splitting your changes into separate pull requests in the future so that we can merge them individually.

Perhaps the transparent background for `main` should be enabled automatically when `stylix.opacity.terminal < 1.0`. This is the same thing we do for Helix. It means users with a transparent terminal get a better experience without having to manually enable it, while at the same time, the solid color background is preserved in other cases for compatibility with unthemed terminals.

2024-08-05 16:06 UTC, trueNAHO commented on modules/neovim/hm.nix
> +    transparent_bg = {
Should we also apply this to:

https://github.com/danth/stylix/blob/feb2973dfa8232c07efbd2b48f11a5cfa2276570/modules/nixvim/nixvim.nix#L10

2024-08-05 16:06 UTC, trueNAHO commented on modules/neovim/hm.nix
> +      sign_column = lib.mkEnableOption "background transparency for the Neovim sign column";
Should we also apply this to:

https://github.com/danth/stylix/blob/feb2973dfa8232c07efbd2b48f11a5cfa2276570/modules/nixvim/nixvim.nix#L12

2024-08-05 16:10 UTC, danth commented on modules/neovim/hm.nix
> +    transparent_bg = {
I didn't notice that this was copied from the NixVim module - ideally yes both modules should use the camelCase format without abbreviations. The NixVim module will need `mkRenamedOptionModule` for backwards compatibility, though renaming those existing options doesn't need to be part of this PR

2024-08-05 16:11 UTC, danth commented on modules/neovim/hm.nix
> +      sign_column = lib.mkEnableOption "background transparency for the Neovim sign column";
See this comment https://github.com/danth/stylix/pull/496#discussion_r1704353280

2024-08-05 16:19 UTC, danth commented
> In that case, we should also apply this to the [NixVim module](https://github.com/danth/stylix/blob/feb2973dfa8232c07efbd2b48f11a5cfa2276570/modules/nixvim/nixvim.nix).

Perhaps there should be a global setting for "remove the solid background from TUI apps" too, with the default following the behaviour I described above. Basically a global version of the `transparentBackground` option introduced here. (Again, that doesn't need to be done in this PR)

2024-08-06 11:41 UTC, danth approved these changes
Going to merge this now since automatic enablement can be added later, and will need to be implemented for NixVim too which is outside the scope of this PR.

2024-08-06 11:42 UTC, merged