neovim: use mini.base16 for colorscheme
danth/stylix pull request #536
Opened 2024-08-28 23:34 UTC by soulsoiledit

Switches both the neovim and nixvim modules to use mini.base16.

Closes #535

2024-08-29 13:16 UTC, trueNAHO requested changes
> ```patch
> From 6fe4ff7a686ae66a23c8040bb4384eccf801aa85 Mon Sep 17 00:00:00 2001
> From: soulsoiledit <no.sleep410@passinbox.com>
> Date: Wed, 28 Aug 2024 18:18:16 -0500
> Subject: [PATCH 1/2] nixvim: use mini.base16 for colorscheme
>
> mini.base16 provides better support for various neovim plugins
> ```

The commit message could be improved to:

```patch
Subject: [PATCH v2 1/2] nixvim: set colorscheme using mini.base16

Set the colorscheme using the mini.base16 plugin for better plugin integration.
```

> ```patch
> ---
>  modules/nixvim/nixvim.nix | 8 ++++----
>  1 file changed, 4 insertions(+), 4 deletions(-)
>
> diff --git a/modules/nixvim/nixvim.nix b/modules/nixvim/nixvim.nix
> index dbc1da66..f6f20bf5 100644
> --- a/modules/nixvim/nixvim.nix
> +++ b/modules/nixvim/nixvim.nix
> @@ -28,14 +28,14 @@
>    config = lib.mkIf (config.stylix.enable && config.stylix.targets.nixvim.enable && (config.programs ? nixvim)) (
>      lib.optionalAttrs (builtins.hasAttr "nixvim" options.programs) {
>        programs.nixvim = {
> -        colorschemes.base16 = {
> -          colorscheme = {
> +        plugins.mini = {
> +          enable = true;
> +
> +          modules.base16.palette = {
>              inherit (config.lib.stylix.colors.withHashtag)
>                base00 base01 base02 base03 base04 base05 base06 base07
>                base08 base09 base0A base0B base0C base0D base0E base0F;
>            };
> -
> -          enable = true;
>          };
>
>          highlight = let
> ```

Unless Nixvim refuses this patch, I would prefer this to be upstreamed to Nixvim, and then we simply update the Nixvim input.

This patch causes the following error without any additional `inputs.stylix.inputs.<INPUTS>.follows` declarations:

```
Error detected while processing /home/<USER>/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/<USER>/.config/nvim/init.lua:81: module 'mini.base16' not found:
        no field package.preload['mini.base16']
        no file '/nix/store/kf5k5qa53g9rrsch256vqgnr7al080al-luajit-2.1.1693350652-env/share/lua/5.1/mini/base16.lua'
        no file '/nix/store/kf5k5qa53g9rrsch256vqgnr7al080al-luajit-2.1.1693350652-env/share/lua/5.1/mini/base16/init.lua'
        no file '/nix/store/kf5k5qa53g9rrsch256vqgnr7al080al-luajit-2.1.1693350652-env/lib/lua/5.1/mini/base16.so'
        no file '/nix/store/kf5k5qa53g9rrsch256vqgnr7al080al-luajit-2.1.1693350652-env/lib/lua/5.1/mini.so'
stack traceback:
        [C]: in function 'require'
        /home/<USER>/.config/nvim/init.lua:81: in main chunk
```

Maybe some Stylix inputs need to be updated.

> ```patch
> From 1e8a1c103bd80c4bcfdbf649db84f71d47df6a53 Mon Sep 17 00:00:00 2001
> From: soulsoiledit <no.sleep410@passinbox.com>
> Date: Wed, 28 Aug 2024 18:20:36 -0500
> Subject: [PATCH 2/2] neovim: use mini.base16 for colorscheme
>
> mini.base16 provides better support for various neovim plugins
> ```

The commit message could be improved to:

```patch
Subject: [PATCH v2 2/2] neovim: replace base16-nvim with mini.base16

Replace the base16-nvim plugin with the mini.base16 plugin for better plugin
integration.
```

> ```patch
> ---
>  modules/neovim/hm.nix | 14 ++++++++------
>  1 file changed, 8 insertions(+), 6 deletions(-)
>
> diff --git a/modules/neovim/hm.nix b/modules/neovim/hm.nix
> index 587c196e..e565ad1d 100644
> --- a/modules/neovim/hm.nix
> +++ b/modules/neovim/hm.nix
> @@ -18,15 +18,17 @@
>        in
>        {
>          plugins = lib.singleton {
> -          plugin = pkgs.vimPlugins.base16-nvim;
> +          plugin = pkgs.vimPlugins.mini-nvim;
>            type = "lua";
>            config = lib.mkMerge [
>              (with config.lib.stylix.colors.withHashtag; ''
> -              require('base16-colorscheme').setup({
> -                base00 = '${base00}', base01 = '${base01}', base02 = '${base02}', base03 = '${base03}',
> -                base04 = '${base04}', base05 = '${base05}', base06 = '${base06}', base07 = '${base07}',
> -                base08 = '${base08}', base09 = '${base09}', base0A = '${base0A}', base0B = '${base0B}',
> -                base0C = '${base0C}', base0D = '${base0D}', base0E = '${base0E}', base0F = '${base0F}'
> +              require('mini.base16').setup({
> +                palette = {
> +                  base00 = '${base00}', base01 = '${base01}', base02 = '${base02}', base03 = '${base03}',
> +                  base04 = '${base04}', base05 = '${base05}', base06 = '${base06}', base07 = '${base07}',
> +                  base08 = '${base08}', base09 = '${base09}', base0A = '${base0A}', base0B = '${base0B}',
> +                  base0C = '${base0C}', base0D = '${base0D}', base0E = '${base0E}', base0F = '${base0F}'
> +                }
>                })
>              '')
>              (lib.mkIf cfg.transparentBackground.main ''
> ```

I have not tested this patch yet.

2024-08-29 19:57 UTC, donovanglover commented
This is how base16.nvim looks for me:

![image](https://github.com/user-attachments/assets/7bc0807c-6fc7-4278-a5c7-f8c08e5965c3)

And this is how mini.nvim looks:

![image](https://github.com/user-attachments/assets/94d88521-7010-4f1d-b461-457d649d2fa5)

Making this change optional would be nice.

2024-08-29 21:21 UTC, trueNAHO commented
> Making this change optional would be nice.

We could add options to enable specific color scheme setters.

@soulsoiledit, can you elaborate on how the algorithms of `base16.nvim` and `mini.nvim` plugins technically differ? For example, the `mini.nvim` plugin already explains its algorithm: https://github.com/echasnovski/mini.base16/blob/95db7f0ea89fbc60b321dbe23d39c1502a07a20e/lua/mini/base16.lua#L223-L257. Based on this comparison we can decide which one should be the default.

2024-08-29 21:31 UTC, soulsoiledit commented
In this context, the algorithms don't differ at all. The algorithm described in mini-base16 only applies when you want to provide a subset of colors, ie only background, foreground, and accent. In that case, it generates a suitable palette based on those colors. 

Since we are providing the full palette, mini.base16 calls this function (https://github.com/echasnovski/mini.base16/blob/95db7f0ea89fbc60b321dbe23d39c1502a07a20e/lua/mini/base16.lua#L446) instead, which does the same thing as base16-nvim, grabbing colors directly from the palette given.

I'm fine with keeping base16-nvim as the default.

2024-08-29 21:40 UTC, trueNAHO commented
> Since we are providing the full palette, mini.base16 calls this function (https://github.com/echasnovski/mini.base16/blob/95db7f0ea89fbc60b321dbe23d39c1502a07a20e/lua/mini/base16.lua#L446) instead, which does the same thing as base16-nvim, grabbing colors directly from the palette given.

In that case, why do the colors look different:

> This is how base16.nvim looks for me:
>
> ![image](https://private-user-images.githubusercontent.com/2374245/362865960-7bc0807c-6fc7-4278-a5c7-f8c08e5965c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Njc2MTksIm5iZiI6MTcyNDk2NzMxOSwicGF0aCI6Ii8yMzc0MjQ1LzM2Mjg2NTk2MC03YmMwODA3Yy02ZmM3LTQyNzgtYTVjNy1mOGMwOGU1OTY1YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMjEzNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJmYzQyNGI4YjljNTAzMDg1ODg3ZDFjNTFmODQ4MWQwYmE3NzFkMTliYmE0ZWJiMTMzMzZjNzNhY2NiM2Q2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PPBUxrXf-d58MwcO5cZ1ulbthvlGkoyr7b8TYIyS-og)
>
> And this is how mini.nvim looks:
>
> ![image](https://private-user-images.githubusercontent.com/2374245/362866122-94d88521-7010-4f1d-b461-457d649d2fa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Njc2MTksIm5iZiI6MTcyNDk2NzMxOSwicGF0aCI6Ii8yMzc0MjQ1LzM2Mjg2NjEyMi05NGQ4ODUyMS03MDEwLTRmMWQtYjQ2MS00NTdkNjQ5ZDJmYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMjEzNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGM4MmRmMzFkY2ZiNGIxYzk2ZTdkMGVjY2E4MTZmZGNmNTM2M2FjNWVkMGMyOGY2ODAyYjRlMzMyM2FkNjRlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5-iAKn6o6SzjyXqn5rzVaLVXuOMecEu5awlWE079oI0)

Is it because the plugin is explicitly themed by `mini.nvim`?

> I'm fine with keeping base16-nvim as the default.

If the premise of `mini.nvim` is to be `base16.nvim` with additional plugin support, then it might be better to make `mini.nvim` the default.

2024-08-29 21:56 UTC, soulsoiledit commented
mini assigns that highlight group, builtin variables such as (this, self, etc), as part of "special symbols" within a language, while base16-nvim assigns them the same as other variables.

2024-08-29 22:01 UTC, trueNAHO commented
> In that case, why do the colors look different:
>
> [...]
>
> Is it because some plugins are explicitly themed by `mini.nvim`?

> mini assigns that highlight group, builtin variables such as (this, self, etc), as part of "special symbols" within a language, while base16-nvim assigns them the same as other variables.

The visible change is probably caused by `mini.nvim`'s intervention with Treesitter. Just search for `tree` in https://github.com/echasnovski/mini.base16/blob/95db7f0ea89fbc60b321dbe23d39c1502a07a20e/lua/mini/base16.lua.

2024-08-30 00:11 UTC, soulsoiledit commented
> This patch causes the following error without any additional inputs.stylix.inputs.<INPUTS>.follows declarations:

I'm not sure what's going on here. I checked the pinned version of nixpkgs in stylix, and the mini.nvim version there does seem to have mini.base16 included.

> Making this change optional would be nice.

I have added this option under `stylix.targets.neovim.plugin` and `stylix.targets.nixvim.plugin`.

2024-08-30 20:24 UTC, trueNAHO commented
> > This patch causes the following error without any additional inputs.stylix.inputs..follows declarations:
>
> I'm not sure what's going on here. I checked the pinned version of nixpkgs in stylix, and the mini.nvim version there does seem to have mini.base16 included.

There is probably something wrong with my setup. I will try to test this tomorrow.

> I have added this option under `stylix.targets.neovim.plugin` and `stylix.targets.nixvim.plugin`.

I performed the following changes to this PR:

- Properly merge commit 8b6d33479ef5 ("neovim: add plugin selection option") into the commits 75394d92ff3f ("nixvim: set colorscheme with mini.base16") and d58790127e38 ("neovim: set colorscheme with mini.base16")
- Rename `stylix.targets.neovim.plugin` to `stylix.targets.neovim.colorscheme`
- Improve `stylix.targets.neovim.colorscheme` description

2024-08-31 17:38 UTC, trueNAHO approved these changes

2024-08-31 17:48 UTC, trueNAHO commented
> I will try to test this tomorrow.

I added my `Tested-by` tag to the NixVim patch.

2024-08-31 19:23 UTC, danth commented
> In that case, why do the colors look different

Ideally the color usage should be as close to [the upstream style guide](https://github.com/tinted-theming/base24/blob/master/styling.md#specific-colours-and-their-usages) as possible. [Our own style guide](https://stylix.danth.me/styling.html) currently just refers to that link when it comes to text editors. Unfortunately, the guide isn't very specific in some cases, such as the example with `this` and `self`, hence the differences as each plugin author has used their own preference.

From the screenshots above, I personally prefer this new plugin since it differentiates between variables and boolean values in Nix, although that's just one of I assume many differences.

![image](https://github.com/user-attachments/assets/0baa2a14-82e0-49db-880b-d6614d930987)
![image](https://github.com/user-attachments/assets/4b58cebb-6792-4f93-af0a-aec094a1e6bf)

According to the upstream guide, nether of these are totally correct - variables should be red and booleans should be yellow (unless @donovanglover's chosen scheme has non-standard colors).

2024-09-01 00:09 UTC, trueNAHO commented
> Ideally the color usage should be as close to [the upstream style guide](https://github.com/tinted-theming/base24/blob/master/styling.md#specific-colours-and-their-usages) as possible. [Our own style guide](https://stylix.danth.me/styling.html) currently just refers to that link when it comes to text editors. Unfortunately, the guide isn't very specific in some cases, such as the example with `this` and `self`, hence the differences as each plugin author has used their own preference.
>
> [...]
>
> According to the upstream guide, nether of these are totally correct - variables should be red and booleans should be yellow (unless @donovanglover's chosen scheme has non-standard colors).

Until the style guide has been expanded [1], it won't hurt to provide a new colorscheme plugin. Once the VIM highlight groups are implemented in Stylix [1], we can replace both colorscheme plugins with the VIM highlight groups.

[1]: https://github.com/danth/stylix/issues/249

2024-09-01 02:34 UTC, donovanglover commented
I think the colors are different due to nvim-lspconfig and treesitter. I mainly like base16-nvim for its usage of italics and other style differences (like `export` being blue in JS/TS) but it does seem different than the spec.

![image](https://github.com/user-attachments/assets/7e17c19a-ce52-4525-92d7-8c6c7517bba2)

Theme is `selenized-black` if anyone wants to try it.

2024-09-27 07:16 UTC, trueNAHO commented
@soulsoiledit, could summarize the status of this PR or what is blocking it from our side?

2024-09-27 12:02 UTC, soulsoiledit commented
On my end, it's  telling me that it needs another review from a non-committer.

2024-09-27 14:02 UTC, soulsoiledit commented
> On my end, it's telling me that it needs another review apart from the last pusher (you).
@danth Could you help out? :)

2024-09-29 18:44 UTC, danth reviewed
Other than my comment below, this looks good to go :))

2024-09-29 18:44 UTC, danth commented on modules/neovim/hm.nix
> +    colorscheme = lib.mkOption {
Could we rename this option to something like `stylix.targets.neovim.plugin`? `colorscheme` feels very generic within a project which is all about colorschemes.

2024-09-30 20:06 UTC, trueNAHO approved these changes
I reviewed both commits and re-tested the Nixvim patch.

2024-10-07 15:09 UTC, trueNAHO commented
@danth, can you do a merge commit for this PR? AFAIK, I only have permission to do squash commits via the GitHub UI.

2024-10-19 23:27 UTC, danth approved these changes

2024-10-19 23:28 UTC, merged

2024-10-19 23:29 UTC, danth commented
@trueNAHO done :)