forge: init
danth/stylix pull request #573
Opened 2024-09-25 21:02 UTC by brckd

Adds border colors to the Forge GNOME extension. It basically makes all focused window borders blue. In contrast to the style guide, unfocused windows don't have a border, because I couldn't find a setting for that.
![image](https://github.com/user-attachments/assets/78113d51-9807-4a8f-9cc6-de63fcc31a08)

This is my first PR here, so sorry for any mistakes in advance. Do I have to import the module somewhere for it to be included? Can I just write to `xdg.configFile` even though the extension might not have been installed?

2024-09-26 14:40 UTC, trueNAHO approved these changes
LGTM: `Approved-by: NAHO <90870942+trueNAHO@users.noreply.github.com>
`.

---

The following comment is purely for reference for https://github.com/danth/stylix/issues/534:

> ```patch
> diff --git a/modules/forge/hm.nix b/modules/forge/hm.nix
> new file mode 100644
> index 00000000..9a9b1f51
> --- /dev/null
> +++ b/modules/forge/hm.nix
> @@ -0,0 +1,13 @@
> [...]
> +  config = lib.mkIf (config.stylix.enable && config.stylix.targets.forge.enable) {
> +    xdg.configFile."forge/stylesheet/forge/stylesheet".source = config.lib.stylix.colors {
> [...]
> +    };
> +  };
> ```

As mentioned in https://github.com/danth/stylix/issues/543, it would be good to reconsider in https://github.com/danth/stylix/issues/534 what functionality should be enabled by default. Maybe `config.lib.stylix.mkEnableTarget` should consider whether the target itself is enabled.

2024-09-26 14:52 UTC, trueNAHO requested changes
> LGTM: `Approved-by: NAHO <90870942+trueNAHO@users.noreply.github.com>`.

Actually, the `modules/forge/stylesheet.css.mustache` file should only declare things related to colors or fonts. There have been some discussions on standardizing border widths, but that will probably be standardized once the [style guide has been formalized](https://github.com/danth/stylix/issues/249).

2024-09-27 07:10 UTC, trueNAHO commented
> Would something along the lines of `config.lib.stylix.mkEnableTarget "Forge" (builtins.elem pkgs.gnome-extensions.forge options.programs.gnome.extensions)` work?

Probably. However, it might be better to not include this in this PR as this is not the current Stylix convention for enabling targets. In the future, this should be addressed with an atomic tree wide patch.

> I will also try to see whether I can just strip the border styling.

Essentially, most hard-coded (not relying on Stylix variables) options should be removed.

2024-09-28 19:27 UTC, brckd commented
I tried simply removing the hardcoded values, but it raised an error in Forge.
![image](https://github.com/user-attachments/assets/181b5206-f6f4-4a78-98b6-23575f73804f)
My next option would be to create a home manager module to configure forge declaratively, but that will be quite the efford.

2024-09-29 09:13 UTC, trueNAHO reviewed
> My next option would be to create a home manager module to configure forge declaratively, but that will be quite the efford.

This is already an acknowledged template limitation:

> the use of `extraConfig` might cause other potentially related issues. As discussed in [#159 (comment)](https://github.com/danth/stylix/issues/159#issuecomment-1937879216), it makes it harder to override options, and as discussed in [#388 (comment)](https://github.com/danth/stylix/pull/388#issuecomment-2126947630), it makes it easier to accidentally override Stylix options.
>
> -- https://github.com/danth/stylix/issues/395

In the future, I will resolve these limitations when [cleaning up the codebase](https://github.com/danth/stylix/issues/534). So I don't mind leaving this as-is for now.

> I tried simply removing the hardcoded values, but it raised an error in Forge.

Does Forge not have default values and requires certain values to be declared? Considering that Stylix is not entirely consistent with hard-coded values, I don't mind merging this as-is. @danth, what do you think?

2024-10-06 19:52 UTC, danth approved these changes
This looks good to merge in its current state (and can be improved on later if necessary)

2024-10-07 11:42 UTC, brckd commented
For transparency, I was just rebasing to master in the last couple of force pushes.

2024-10-07 14:47 UTC, trueNAHO approved these changes
I didn't test this, but LGTM:

```
Approved-by: NAHO <90870942+trueNAHO@users.noreply.github.com>
```

2024-10-07 14:49 UTC, merged