fix(foot): disable faulty check
danth/stylix pull request #576
Opened 2024-09-26 23:44 UTC by Mikilio

This solves #571. But since this is only a temporary fix, it does not need to be merged. See https://github.com/SenchoPens/base16.nix/issues/15

There may be a way to do this better, but at least it works for me.

2024-09-27 07:22 UTC, trueNAHO commented
> This solves #571. But since this is only a temporary fix, it does not need to be merged. See [SenchoPens/base16.nix#15](https://github.com/SenchoPens/base16.nix/issues/15)

Unless we need to update this input or users override this input with `follows`, the mentioned issue should not cause any problems.

> There may be a way to do this better, but at least it works for me.

It might be easier and better to wait some time for a potential upstream fix. If this becomes a bigger problem and upstream takes too long to fix this, we could apply this temporary hotfix.

2024-09-27 11:23 UTC, Mikilio commented
I agree.

2024-10-09 16:19 UTC, anotherhadi commented
The issue is still there, how to use your pull request as the flake input?

2024-10-09 16:26 UTC, psynyde commented
> The issue is still there, how to use your pull request as the flake input?

You need to change input to the pr is coming from (ie `https://github.com/Mikilio/stylix/tree/temp-fix-foot` in this case).
Although note that this repo is behind some commits compared to `master` branch here.

2024-10-09 16:29 UTC, psynyde commented
> The issue is still there, how to use your pull request as the flake input?

You need to change the input to the repo where the pr is coming from (ie `github:Mikilio/stylix/temp-fix-foot' in this case).
Note that the repo is behind some commits compared to `master` branch here

2024-11-04 01:48 UTC, Mikilio commented
Apparently this is still an issue.

2024-11-04 02:23 UTC, Mikilio commented
So I've changed the fix to simply pinning the tinted-theming/foot repo. Maybe this can actually be merged?

2024-11-04 16:10 UTC, danth requested changes

2024-11-07 15:17 UTC, trueNAHO requested changes
Aside from the copy-paste mistake, this PR LGTM:

```
Reviewed-by: NAHO <90870942+trueNAHO@users.noreply.github.com>
```

2024-11-08 18:08 UTC, danth approved these changes
Looks good to me :))

2024-11-08 18:22 UTC, trueNAHO approved these changes
```
Reviewed-by: NAHO <90870942+trueNAHO@users.noreply.github.com>
```

2024-11-08 18:26 UTC, merged

2024-11-09 07:12 UTC, Mikilio commented
```
unpacking 'github:tinted-theming/tinted-foot/fd1b924b6c45c3e4465e8a849e67ea82933fcbe4' into the Git cache...
error:
       … while updating the lock file of flake 'github:danth/stylix/655528278fd89fd7f3149f47fdca994b08dd0b71?narHash=sha256-Jg7peqzVbv4ULKNyx9wVIevsLbycDWfSfGpqheX06dc%3D'

       error: cannot write modified lock file of flake 'github:danth/stylix/655528278fd89fd7f3149f47fdca994b08dd0b71' (use '--no-write-lock-file' to ignore)
```

Well, I did not update the lockfile. That much is true.
So maybe it should be updated for the CI?
A simple `nix flake lock --update-input tinted-foot` should suffice (did not check for typos).