Add options to set fonts
danth/stylix pull request #60
Opened 2023-03-09 15:22 UTC by dwarfmaster

To fix #35 and #59 , we need a way to specify font sizes. I think the best approach is to select a nomenclature of font sizes that could be reused by modules. Here I propose one such nomenclature to start discussions. Once the nomenclature is agreed upon, we can update the modules to use it.

2023-03-10 14:39 UTC, danth commented
If I was writing this I would have had a single size for each font (serif, sans-serif, monospace), but I think your choices provide a bit more flexibility.

2023-03-14 14:48 UTC, dwarfmaster commented
I haven't tested everything in depth, but it should work.

2023-03-16 09:24 UTC, danth requested changes
Looks like there is an issue with the Sway module:

```
error: A definition for option `home-manager.users.danth.wayland.windowManager.sway.config.fonts.size' is not of type `floating point number'. Definition values:
       - In `/nix/store/d8dfhghz782by1524kg8jwhjqmmv4hp3-modules/sway/hm.nix': 10
```

2023-03-16 09:41 UTC, dwarfmaster commented
I didn't know nix distinguished integers and floating points, I'll fix that.

2023-03-19 18:38 UTC, danth approved these changes
Works with my configuration now.

2023-03-19 18:39 UTC, merged