zed: added zed hm module
danth/stylix pull request #620
Opened 2024-11-11 21:35 UTC by TheYoxy

Add [zed editor](https://zed.dev) module support.

Closes: https://github.com/danth/stylix/issues/348

2024-11-12 00:56 UTC, trueNAHO requested changes

2024-11-12 00:56 UTC, trueNAHO commented on modules/zed/hm.nix
> +  inputs,
> Unused lambda pattern: inputs

```suggestion
```

2024-11-12 00:56 UTC, trueNAHO commented on modules/zed/hm.nix
> +      };
As already discussed in https://github.com/danth/stylix/pull/388, Stylix should not declare options with `lib.mkDefault`.

2024-11-12 00:56 UTC, trueNAHO commented on modules/zed/hm.nix
> +    };
Consider simplifying the attribute set declaration:

```suggestion
    xdg.configFile."zed/themes/nix.json".source = theme;
```

2024-11-12 00:56 UTC, trueNAHO commented on modules/zed/hm.nix
> +      userSettings = {
Consider simplifying the attribute set declaration:

```suggestion
    programs.zed-editor.userSettings = {
```

2024-11-12 00:56 UTC, trueNAHO commented on modules/zed/hm.nix
> +  };
Consider simplifying the attribute set declaration:

```suggestion
  options.stylix.targets.zed.enable =
    config.lib.stylix.mkEnableTarget "zed" true;
```

2024-11-12 12:18 UTC, trueNAHO commented
> I've seen that the current version of home-manager from flake.lock doesn't contains any references to zed-editor yet. Should it be updated from this pr or should I mark this pr as stale waiting from this update ?

Update `/flake.lock` in this PR.

2024-11-14 07:59 UTC, trueNAHO commented on flake.lock
> +        "rev": "fd1b924b6c45c3e4465e8a849e67ea82933fcbe4",
Consider rebasing on top of commit https://github.com/danth/stylix/commit/be94701ce7b746cb020e667f71492e398ed470f4.

2024-11-17 12:35 UTC, trueNAHO requested changes
The CI is failing:

> ```
> error: attribute 'zed-editor' missing
> at /nix/store/g2ia4fjmdkbjrxbrmwhj4q62bysym489-modules/zed/hm.nix:12:82:
>     11|
>     12|   config = lib.mkIf (config.stylix.enable && config.stylix.targets.zed.enable && config.programs.zed-editor.enable) {
>       |                                                                                  ^
>     13|     programs.zed-editor.userSettings = {
> Error: Process completed with exit code 1.
> ```

Maybe the current `/flake.lock` still does not include the Zed module.

2024-11-18 15:40 UTC, trueNAHO commented
> Yeah, I'll keep it stale until flake.lock is updated with hm version that supports the zed-editor.

AFAIK, commit cf5be812bdc889f10ada644e4736138c5757e1e9 contains the `zed-editor` module in Home Manager. Consider rebasing on top of `master`.

2025-01-01 13:12 UTC, Lalit64 commented
Hey, any updates

2025-01-01 18:46 UTC, trueNAHO commented
@TheYoxy, can you `git rebase master` and update the necessary inputs for this PR to work? I assume everything should be available on upstream by now.

2025-01-06 15:18 UTC, trueNAHO approved these changes
> Sorry for the delay, I was in holiday break.

No worries.

> I've rebased the branch on the master from upstream, built on my side and should be good now

I added commit 0f2ee2595381 ("zed: format code") to make the following test pass:

```console
nix build github:TheYoxy/stylix/feature/zed#checks.x86_64-linux.git-hooks
```

For reference, the following test passes on commit 80e3b554b98d ("zed: sort attributes"):

```console
nix run .#nix-flake-check
```

2025-01-06 15:21 UTC, merged