Don't split autoloaded modules into a separate derivation
danth/stylix pull request #631
Opened 2024-11-16 09:36 UTC by binarin

Apparently `../modules` is creating a separate derivation that contains only that folder, so it's now separate from the  flake source. But this transient derivation isn't mentioned explicitly anywhere in the flake outputs. It makes it impossible to target those modules in `disabledModules` directive.

For example, after this change is applied, users can solve issues like https://github.com/danth/stylix/issues/577 locally, by just adding the following snippet to their configuration:

    disabledModules = [ "${inputs.stylix}/modules/regreet/nixos.nix" ];

2024-11-17 15:44 UTC, trueNAHO requested changes
Good job!

I have only one formatting nitpick.

2024-11-17 15:44 UTC, trueNAHO commented on docs/src/tricks.md
> +
```suggestion
imports = [ flake.inputs.stylix.nixosModules.stylix ];
disabledModules = [ "${flake.inputs.stylix}/modules/<some-module>/nixos.nix" ];
```

2024-11-17 16:10 UTC, danth approved these changes
Looks good to me :))

2024-11-17 16:40 UTC, merged

2025-05-27 01:14 UTC, MattSturgeon commented
I believe the underlying issue here is **not** that you should use `self` instead of relative paths, but rather that using [string interpolation](https://nix.dev/manual/nix/2.28/language/string-interpolation) on a path will copy it to the store.

I.e. importing modules like `"${somePath}/foo/bar"` will cause `somePath` to be copied to the store.

Instead, you should use either `somePath + "/foo/bar"` or `"${toString somePath}/foo/bar"` to avoid the copy-to-store.

To clarify, the issue with copying a specific path to the store is that it gets its own store object, which is a distinct path unrelated to stylix's "root" store object represented by `self` or `./.` in the root of the flake.

This issue can be better fixed by removing all path-to-string interpolation and going back to using relative paths, instead explicitly of interpolating `self` and needing to pass `self` or `inputs` into your modules.