ci: fail build if the lockfile is out of sync
danth/stylix pull request #674
Opened 2024-12-10 18:49 UTC by danth

Following the discussion in #671, this will fail the CI workflow if an input in `flake.lock` is updated to a revision which isn't on the branch specified in `flake.nix`. This prevents accidentally updating the release branch to use an unstable Nixpkgs revision.

2024-12-10 19:23 UTC, trueNAHO requested changes
> this will fail the CI workflow if an input in `flake.lock` is updated to a revision which isn't on the branch specified in `flake.nix`.

While this change is in fact an improvement, I think it does something else:

> · --no-update-lock-file
>
>   Do not allow any updates to the flake's lock file.
>
> -- nix3-build(1)

Suppose that `<NEW_HASH>` refers to a valid commit more up-to-date than anything on `master` or `release-24.11`.

In that case, a backport updating `nodes.nixpkgs.locked.rev` in `flake.lock` will update the input version without `nix build` or `nix build --no-update-lock-file` reporting anything.

A backport updating `inputs.nixpkgs.url` in `flake.nix` without touching `nodes.nixpkgs.locked.rev` in `flake.lock`, causes `nix build` to write to `flake.lock` in order to update `nodes.nixpkgs.locked.rev` and causes nix build --no-update-lock-file` to fail when attempting to update `nodes.nixpkgs.locked.rev`.

I don't think there currently exists any tool that verifies whether `nodes.<INPUT>.locked.rev` is on the branch of `inputs.<INPUT>.url`.

I suggest updating the commit title and commit message accordingly, and get this PR merged.

2024-12-10 19:31 UTC, danth commented
You're correct.

The reason it worked in my test was because I copied the entire `flake.lock` from `master`, which has the different branch name recorded in the lock file too.

However, this is still useful to detect when `flake.nix` is changed without updating `flake.lock`, for example when editing through the GitHub website.

2024-12-10 22:27 UTC, trueNAHO commented
> ci: ensure branch names in flake.lock match flake.nix

I think the `--no-update-lock-file` option prevents more general `rev`ision mistmatches rather than just branch mistmatches.

Consequently, I set the commit message to the following:

```
ci: prevent unexpected flake.nix and flake.lock inconsistencies (#674)

Prevent some unexpected flake.nix and flock.lock revision
inconsistencies by building configurations with the
--no-update-lock-file option:

> --no-update-lock-file
>
> Do not allow any updates to the flake's lock file.
>
> -- nix3-build(1)

Link: https://github.com/danth/stylix/pull/674

Reviewed-by: NAHO <90870942+trueNAHO@users.noreply.github.com>
```

@danth, if this is fine for you, ping me so I can approve this in the GitHub UI for this PR to get merged with this commit message.

2024-12-12 14:07 UTC, danth commented
@trueNAHO LGTM :))

2024-12-12 14:09 UTC, trueNAHO approved these changes

2024-12-12 14:09 UTC, merged