wpaperd: fix image scaling modes
danth/stylix pull request #710
Opened 2024-12-30 07:19 UTC by hazelmeow

Previously, the `fill` image scaling mode would use `fit` in wpaperd, which scales the image to fit within the screen without cropping it. This PR uses wpaperd's `center` mode instead which is closer to swaybg's `fill` mode (scales the image to fill the screen, potentially cropping).

See https://github.com/danyspin97/wpaperd#wallpaper-configuration

2024-12-31 17:31 UTC, trueNAHO requested changes

2024-12-31 17:31 UTC, trueNAHO commented on modules/wpaperd/hm.nix
> +        if imageScalingMode == "stretch"
Could you add an explanatory comment?

2025-01-02 19:11 UTC, hazelmeow commented on modules/wpaperd/hm.nix
> +        if imageScalingMode == "stretch"
Added some comments.

2025-01-02 19:23 UTC, trueNAHO commented on modules/wpaperd/hm.nix
> +        then null
Would the following improve the UX or not:

```suggestion
        then
          lib.info
          "[stylix] wpaperd has not equivalent center mode for scaling the image"
          null
```

2025-01-03 19:43 UTC, hazelmeow commented on modules/wpaperd/hm.nix
> +        then null
Added the warning. Actually, `formats.toml` was complaining when there was a null value, so I changed the structure around a bit. I'm not super experienced with nix so lmk if there's a better way to do it.

2025-01-03 20:14 UTC, trueNAHO commented on modules/wpaperd/hm.nix
> +        then null
> Actually, `formats.toml` was complaining when there was a null value

What file are you referring to? Is this in your setup?

> I changed the structure around a bit. I'm not super experienced with nix so lmk if there's a better way to do it.

Since we do not have an abstraction layer on top of `stylix.imageScalingMode`, we might want to keep it simple with a series of if-else expression, as before.

2025-01-07 03:52 UTC, hazelmeow commented on modules/wpaperd/hm.nix
> +        then null
When I set `mode = null;` I get `A definition for option `home-manager.users.hazel.programs.wpaperd.settings.any.mode' is not of type `TOML value'`. So I think it needs to be unset rather than null which is why I changed it. I can make it a series of if-else expressions, but I'm not sure how else to do it besides merging the attrsets.

2025-01-07 18:19 UTC, trueNAHO commented on modules/wpaperd/hm.nix
> +        then null
Alright. The current approach sounds good to me then.

2025-01-07 18:21 UTC, trueNAHO requested changes
Can you `git rebase master` and make sure the CI is passing? You can test the formatters and linters locally with `nix build .#checks.x86_64-linux.git-hooks`.

2025-01-13 17:36 UTC, hazelmeow commented
@trueNAHO could you take a look again?

2025-01-18 11:29 UTC, trueNAHO approved these changes
LGTM.

Sorry for the delay.

2025-01-18 11:36 UTC, merged

2025-01-18 19:46 UTC, hazelmeow commented
Thanks!